### ISSUE TITLE
生成的图片文件名编号问题导致PDF页面错乱

### ISSUE THREAD

**Issue by tmeppp** [GallenQiu/-book118-#2]
比如下载的资料名为：Python教程，则生成的图片文件名为：Python教程1.png,Python教程2.png.......
但生成PDF时，实际顺序是：Python教程1.png，Python教程10.png，Python教程11.png，Python教程12.png，修改也很简单把
run.py中  with open('图片//'+str(self.title).split('.')[0]+str(c)+'.png','wb+')as f:
改为     with open('图片//'+str(self.title).split('.')[0]+str(c).zfill(n)+'.png','wb+')as f:  
其中n就是根据总网址数量前加1个或两个0，生成Python教程01.png或者Python教程001.png就可以了

**Comment by Jayshanx** [comment]
@tmeppp  谢谢， 但 mac 环境下按照你这种方法依然是乱的顺序
解决方法： 
在img.py 的 73行之后加一行 
`  filenames.sort()`
对filenames 排下序就好了
